Gidon
erelsgl/fairpy pull request #21
Opened 2022-06-11 19:13 UTC by gidon285

2022-06-11 19:14 UTC, gidon285 commented
hi erel, im finished with my algorithm, dont know if i will have time to finish the website demonstration but heres the final product.

2022-06-12 18:29 UTC, gidon285 commented
hi , i fixed the doctest cases, and added some new explanations.

2022-06-13 19:24 UTC, erelsgl requested changes

2022-06-13 19:24 UTC, erelsgl commented on fairpy/items/fair_division_under_cardinality_constraints.py
> +"""
תוסיף את השם שלך + תאריך

2022-06-13 19:24 UTC, erelsgl commented on fairpy/items/fair_division_under_cardinality_constraints.py
> +def ef1_algorithm(agents_names:list, f: Data) -> dict:
שם הפרמטר f לא ברור. גם לא ברור למה צריך את הסוג Data - למה לא פשוט להעביר כל פרמטר בנפרד?

2022-06-13 19:24 UTC, erelsgl commented on fairpy/items/fair_division_under_cardinality_constraints.py
> +    """
אחד הפרמטרים לאלגוריתם הוא מספר החפצים שכל שחקן יכול להחזיק מכל קטגוריה (זו המשמעות של cardinality constraint). איפה הפרמטר הזה במימוש שלך?

2022-06-13 19:24 UTC, erelsgl commented on fairpy/items/fair_division_under_cardinality_constraints.py
> +    """
תוסיף דוגמה עם מספר גדול יותר של חפצים בקטגוריה, כך שכל שחקן מקבל יותר מחפץ אחד.

2022-06-13 19:24 UTC, erelsgl commented on fairpy/items/fair_division_under_cardinality_constraints.py
> +def generate_envy(envy_graph:nx.DiGraph, evaluation:dict, category:str, allocation:dict):
הפונקציה לא מייצרת קנאה אלא את גרף הקנאה. עדיף לקרוא לה
generate_envy_graph.
והיא לא צריכה לקבל גרף כפרמטר, אלא ליצור ולהחזיר גרף חדש.

2023-01-14 20:58 UTC, closed without merging