Implementation of min_makespan 2-apprx algo
erelsgl/fairpy pull request #25
Opened 2023-01-10 07:21 UTC by CyberSrul

all done, everything works. passes extensive tests

2023-01-11 12:12 UTC, CyberSrul commented
min makespan 2 apprx algo

2023-01-14 21:32 UTC, erelsgl requested changes

2023-01-14 21:32 UTC, erelsgl commented on fairpy/items/min_makespan.py
> +# data structures
התיעוד צריך להיות בראש הקובץ, הוא צריך לכלול את שם המאמר ואת שם המתכנת, והפורמט שלו צריך להיות כמו בשאר הקבצים בספריה, למשל כאן:

https://github.com/erelsgl/fairpy/blob/master/fairpy/items/approximation_maximin_share.py

2023-01-14 21:32 UTC, erelsgl commented on fairpy/items/min_makespan.py
> +# psedu random functions
לא צריך לשים תיעוד לספריות שמייבאים, בפרט כאשר הן מוכרות וידועות.

2023-01-14 21:32 UTC, erelsgl commented on fairpy/items/min_makespan.py
> +class scedual:
הכתיב הנכון הוא schedule. יש לתקן לאורך כל שני הקבצים.

2023-01-14 21:32 UTC, erelsgl commented on fairpy/items/min_makespan.py
> +def min_makespan(input: ValuationMatrix) -> Allocation:
כיוון שזו הפונקציה הראשית, יש לשים אותה בראש הקובץ. ויש לסמן בבירור לאחר מכן, ששאר הפונקציות הן פונקציות פנימיות.

2023-01-14 21:32 UTC, erelsgl commented on fairpy/items/min_makespan.py
> +        <BLANKLINE>
יש להוסיף דוגמה של קריאה לפונקציה בעזרת fairpy.divide, כמו שמוסבר ברידמי של הספריה.

2023-01-14 21:32 UTC, erelsgl commented on fairpy/items/min_makespan.py
> +# data structures
שם הקובץ, ושם הפונקציה הראשית, לא צריכים להיות min_makespan כי הפונקציה לא תמיד מוצאת את המינימום. אפשר לקרוא לקובץ ולפונקציה הראשית על-שם מחברי המאמר:
lenstra_shmoys_tardos_2approximation

2023-01-14 21:32 UTC, erelsgl commented on fairpy/items/min_makespan_demo.py
> +from fairpy.items.min_makespan import *
הקובץ ששמו מסתיים ב _demo אמור לכלול דוגמאות פשוטות של קריאה לפונקציה הראשית בעזרת fairpy.divide, כמו שמוסבר ברידמי של הספריה. לדוגמה, כמו כאן:
https://github.com/erelsgl/fairpy/blob/master/fairpy/items/propm_allocation_demo.py

הבדיקות המקיפות והחשובות שבקובץ זה אמורות להיות בקובץ ששמו מסתיים ב _test.

2023-01-14 21:32 UTC, erelsgl commented on fairpy/items/min_makespan.py
> +def RandomTesting(algo: MinMakespanAlgo, iterations: int, **kwargs):
המחלקה הזאת לא צריכה להיות כאן, אלא בקובץ השני (של הבדיקות).

2023-01-14 21:32 UTC, erelsgl commented on fairpy/items/min_makespan.py
> +def compare(algo1: Tuple[MinMakespanAlgo, Dict[str, Any]], algo2: Tuple[MinMakespanAlgo, Dict[str, Any]], iterations: int) -> Tuple[int, int]:
נראה שהפונקציה הזאת נועדה לבדיקות בלבד. אם כן,יש להעביר אותה לקובץ השני.

2023-01-14 21:32 UTC, erelsgl commented on fairpy/items/min_makespan.py
> +from numpy.random import randint, uniform
נראה שהפונקציות האלה נועדו לבדיקות בלבד. אם כן, יש להעביר אותן לקובץ השני.

2023-01-14 21:32 UTC, erelsgl commented on fairpy/items/min_makespan_demo.py
> +            self.assertTrue(self.scd.makespan <= 2 * optimum)
הבדיקה הזאת נכשלה אצלי כמה פעמים. צריך לוודא שכאשר הבדיקה נכשלת, הקלט האקראי נכתב למסך, כך שיהיה אפשר לברר למה זה נכשל.

2023-01-29 20:28 UTC, erelsgl requested changes

2023-01-29 20:28 UTC, erelsgl commented on fairpy/items/min_makespan_2apprximation.py
> +logging_format = '%(levelname)s - %(message)s'
כל השורות הקשורות לתצורת הלוג הגלובלית לא צריכות להיות כאן, אלא רק בתוכנית הראשית.

2023-01-29 20:28 UTC, erelsgl commented on fairpy/items/min_makespan_2apprximation.py
> +Jan Karel Lenstra, David, B. Shmoys and Eva Tardo.
בדוק שוב את שמות המחברים

2023-01-29 20:28 UTC, erelsgl commented on fairpy/items/min_makespan_2apprximation.py
> +        Both as the actuall scedualing and the makespan.
יש לתקן שגיאות באנגלית - העזר ב grammarly או כלי אחר.

2023-01-29 20:28 UTC, erelsgl commented on fairpy/items/min_makespan_2apprximation_demo.py
> +print('deals well with dummy caces:\n')
יש לתקן שגיאות באנגלית - אפשר להעזר בכלי כגון grammarly.

2023-01-31 10:19 UTC, CyberSrul commented
למה אתה מתכוון בתוכנית ראשית ? הדמו ? הטסטים ?
בדקתי את שמות המחברים של המאמר, לא הבנתי איפה הטעות אלא אם כן התכוונת לפסיק
ששמתי במקום הלא נכון

On Sun, Jan 29, 2023 at 10:28 PM Erel Segal-Halevi ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In fairpy/items/min_makespan_2apprximation.py
> <https://github.com/erelsgl/fairpy/pull/25#discussion_r1090046087>:
>
> > +
>
> +from fairpy import ValuationMatrix, Allocation, AllocationMatrix, divide
>
> +
>
> +import numpy as np
>
> +from numpy.random import randint, uniform
>
> +import cvxpy as cp
>
> +import networkx as nx
>
> +
>
> +from typing import Callable, Iterator, Tuple
>
> +from itertools import product
>
> +from copy import copy
>
> +import logging
>
> +
>
> +logger = logging.getLogger(__name__)
>
> +
>
> +logging_format = '%(levelname)s - %(message)s'
>
>
> כל השורות הקשורות לתצורת הלוג הגלובלית לא צריכות להיות כאן, אלא רק בתוכנית
> הראשית.
> ------------------------------
>
> In fairpy/items/min_makespan_2apprximation.py
> <https://github.com/erelsgl/fairpy/pull/25#discussion_r1090046124>:
>
> > @@ -0,0 +1,423 @@
>
> +'''
>
> +Find 2 approximation min makespan on unrelated parallel machines.
>
> +Based on:
>
> +
>
> +Jan Karel Lenstra, David, B. Shmoys and Eva Tardo.
>
>
> בדוק שוב את שמות המחברים
> ------------------------------
>
> In fairpy/items/min_makespan_2apprximation.py
> <https://github.com/erelsgl/fairpy/pull/25#discussion_r1090046157>:
>
> > +
>
> +stream_handler = logging.StreamHandler()
>
> +stream_handler.setLevel(logging.ERROR)
>
> +formatter = logging.Formatter(logging_format)
>
> +stream_handler.setFormatter(formatter)
>
> +logger.addHandler(stream_handler)
>
> +
>
> +
>
> +
>
> +" The Main Method "
>
> +
>
> +def min_makespan_2apprximation(input: ValuationMatrix) -> Allocation:
>
> +
>
> +    '''
>
> +        This method returns a 2-approximation of the optimal minimum makespan.
>
> +        Both as the actuall scedualing and the makespan.
>
>
> יש לתקן שגיאות באנגלית - העזר ב grammarly או כלי אחר.
> ------------------------------
>
> In fairpy/items/min_makespan_2apprximation_demo.py
> <https://github.com/erelsgl/fairpy/pull/25#discussion_r1090046223>:
>
> > +                        [30, 9, 12]])
>
> +
>
> +print('classic input\n', input, '\nopt: 9\nresult:')
>
> +print(divide(min_makespan_2apprximation, input))
>
> +
>
> +
>
> +input = ValuationMatrix([[6, 2, 4],
>
> +                         [2, 1, 3],
>
> +                         [3, 2, 8]])
>
> +
>
> +print('another input:\n', input, '\nopt: 4\nresult:')
>
> +print(divide(min_makespan_2apprximation, input))
>
> +
>
> +print(divide(min_makespan_2apprximation, input))
>
> +
>
> +print('deals well with dummy caces:\n')
>
>
> יש לתקן שגיאות באנגלית - אפשר להעזר בכלי כגון grammarly.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/erelsgl/fairpy/pull/25#pullrequestreview-1274293138>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4RWNJZKNKTHMYS26A5AXQTWU3HFZANCNFSM6AAAAAATWKSMCU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-01-31 10:59 UTC, erelsgl commented
"תוכנית ראשית" זה גם הדמו, וגם הקוד שמופיע אחרי 
```
if __name__=="__main__":
```

2023-01-31 11:37 UTC, erelsgl commented
יש טעות גם בכותרת של המאמר ובקישור למאמר. הקישור הנכון הוא: https://link.springer.com/article/10.1007/BF01585745
ושם המחברת האחרונה הוא Eva **Tardos**.

2023-01-31 14:54 UTC, CyberSrul commented
OK, I commited the last requests

2023-01-31 15:15 UTC, merged