Added 2 algorithms
erelsgl/fairpy pull request #27
Opened 2023-01-12 11:14 UTC by noamya-sh

We would be happy to add the two algorithms - an algorithm for a envy-free and equal division, and an approximation algorithm for a ε-envy-free division.

2023-01-14 21:51 UTC, erelsgl requested changes

2023-01-14 21:51 UTC, erelsgl commented on fairpy/items/envy_free_approximation_division.py
> +import doctest
יש להוסיף את בדיקות היחידה שכתבתם בקבצים ששמם כשם הקבצים של האלגוריתם אבל עם סיומת _test. 

בנוסף, יש להוסיף קבצים עם סיומת _demo הכוללים הדגמה של שימוש באלגוריתם בעזרת הפונקציה `fairpy.divide`, כמו שמוסבר ברידמי של הספריה. 

לדוגמה:
 https://github.com/erelsgl/fairpy/blob/master/fairpy/items/propm_allocation_demo.py

2023-01-14 21:51 UTC, erelsgl commented on fairpy/items/envy_free_approximation_division.py
> +"""
ההערה עם שם המאמר והמחברים צריכה להיות בראש הקובץ.

2023-01-14 21:51 UTC, erelsgl commented on fairpy/items/envy_freeness_and_equitability_with_payments.py
> +    doctest.testmod(verbose=True)
Change to "print(doctest.testmod())"

2023-01-14 21:51 UTC, erelsgl commented on fairpy/items/envy_free_approximation_division.py
> +    doctest.testmod()
Change to "print(doctest.testmod())"

2023-01-14 21:51 UTC, erelsgl commented on fairpy/items/envy_free_approximation_division.py
> +def envy_free_approximation_division(allocation: Allocation, eps: float = 0) -> dict:
בנוסף לפונקציה הזאת, צריכה להיות פונקציה ראשית שמבצעת את כל החלוקה מההתחלה. למשל, מתחילה מחלוקה שרירותית כלשהי, או מחלוקה הממקסמת את סכום הערכים.

צריך שתהיה אפשרות לקרוא לפונקציה הראשית בעזרת `fairpy.divide`, כמוסבר ברידמי של הספריה.

הפונקציה הראשית צריכה להיות הפונקציה הראשונה בקובץ, ומתחתיה כל הפונקציות הפנימיות.

2023-01-14 21:51 UTC, erelsgl commented on fairpy/items/envy_freeness_and_equitability_with_payments.py
> +    """
ההערה עם שם המאמר והמחברים צריכה להיות בראש הקובץ.

2023-01-14 21:51 UTC, erelsgl commented on fairpy/items/envy_freeness_and_equitability_with_payments.py
> +eval_1 = {"a": {"x": 40, "y": 20, "r": 30, "rx": 80, "rxy": 100}, "b": {"x": 10, "y":30, "r": 70, "rx": 79, "rxy": 90}}
יש להעביר את כל הבדיקות לקובץ הבדיקות.

2023-01-14 21:51 UTC, erelsgl commented on fairpy/items/envy_freeness_and_equitability_with_payments.py
> +def envy_freeness_and_equitability_with_payments(evaluation: dict, allocation: Allocation):
הפונקציה הראשית צריכה לקבל AgentList, כמו שאר הפונקציות בספריה, וכמו שמוסבר ברידמי של הספריה.

והיא צריכה להיות הפונקציה הראשונה בקובץ.

2023-01-15 09:20 UTC, eitansh28 commented on fairpy/items/envy_free_approximation_division.py
> +import doctest
להוסיף ממש את הקבצים עצמם של הבדיקות, או רק לקחת משם טסטים לקובץ שלנו לdoctest? 
הטסטים שכתבנו בזמנו לא כ"כ רלוונטים מבחינת המימוש הסופי שלנו, גם מבחינת סיבוכיות וגם מבחינה טכנית (סוגי קלט, פלט וכו)

2023-01-15 09:20 UTC, eitansh28 commented on fairpy/items/envy_freeness_and_equitability_with_payments.py
> +eval_1 = {"a": {"x": 40, "y": 20, "r": 30, "rx": 80, "rxy": 100}, "b": {"x": 10, "y":30, "r": 70, "rx": 79, "rxy": 90}}
אתה מתכוון לשורה 177 ומעלה?

2023-01-15 09:22 UTC, noamya-sh commented on fairpy/items/envy_free_approximation_division.py
> +def envy_free_approximation_division(allocation: Allocation, eps: float = 0) -> dict:
מה הכוונה? הבעיה היא שנדרשת חלוקה ולא סתם רשימת משאבים וערכים? לעשות פונקציה שמייצרת חלוקה רנדומית?

2023-01-15 09:46 UTC, eitansh28 commented on fairpy/items/envy_freeness_and_equitability_with_payments.py
> +def envy_freeness_and_equitability_with_payments(evaluation: dict, allocation: Allocation):
בתוך הallocation והevaluation כבר מופיעים כל הסוכנים, למה צריך להכניס אותם בקלט כרשימה? אין לנו בעיה סתם להוסיף אבל לא יהיה לזה באמת שימוש בפונקציה..

2023-01-15 14:03 UTC, erelsgl commented on fairpy/items/envy_free_approximation_division.py
> +import doctest
התכוונתי לקבצים עצמם - תתאימו אותם למימוש הסופי. 
אמורות להיות שם בדיקות-יחידה בעזרת unittest
הבודקות מקרי-קצה, וכן בעיות אקראיות גדולות.

2023-01-15 14:05 UTC, erelsgl commented on fairpy/items/envy_free_approximation_division.py
> +def envy_free_approximation_division(allocation: Allocation, eps: float = 0) -> dict:
תסתכלו על הפונקציות האחרות בספריה: רובן מקבלות כקלט רשימת סוכנים (AgentList) או מטריצת ערכים (ValuationMatrix), ומחזירות חלוקה.
גם אצלכם צריכה להיות פונקציה כזאת, שמקבלת כקלט רשימת-סוכנים או מטריצת ערכים בלבד. 
הפונקציה הזאת יכולה להתחיל מחלוקה שרירותית כלשהי, ואז לקרוא לפונקציה שלכם.

2023-01-15 14:06 UTC, erelsgl commented on fairpy/items/envy_freeness_and_equitability_with_payments.py
> +eval_1 = {"a": {"x": 40, "y": 20, "r": 30, "rx": 80, "rxy": 100}, "b": {"x": 10, "y":30, "r": 70, "rx": 79, "rxy": 90}}
כן, זה שייך לקובץ של הבדיקות (_test) או לקובץ של ההדגמה (_demo).

2023-01-15 14:07 UTC, erelsgl commented on fairpy/items/envy_freeness_and_equitability_with_payments.py
> +def envy_freeness_and_equitability_with_payments(evaluation: dict, allocation: Allocation):
כמו שכתבתי למעלה, צריך להוסיף פונקציה ראשית שלא מקבלת Allocation,
אלא מקבלת רק AgentList או ValuationMatrix.

2023-01-15 15:36 UTC, noamya-sh commented on fairpy/items/envy_free_approximation_division.py
> +def envy_free_approximation_division(allocation: Allocation, eps: float = 0) -> dict:
אבל האלגוריתמים שלנו מתחילים מחלוקה, לא מרשימת סוכנים. כך זה במאמר המקור.

2023-01-15 16:29 UTC, erelsgl commented on fairpy/items/envy_free_approximation_division.py
> +def envy_free_approximation_division(allocation: Allocation, eps: float = 0) -> dict:
נכון, הפונקציות שכתבתם טובות ומתאימות למאמר, אבל כדי להשתלב בספריה צריך להתאים גם למה שמקובל בספריה.
ובמקרה הזה זה מאד פשוט - אפשר להשאיר את הפונקציות שלכם כמו שהן, רק להוסיף עוד פונקציה שיוצרת חלוקה שרירותית וקוראת להן.

2023-01-15 17:20 UTC, eitansh28 commented on fairpy/items/envy_free_approximation_division.py
> +def envy_free_approximation_division(allocation: Allocation, eps: float = 0) -> dict:
אז איזה באיזה שם לקרוא לפונקציה הראשית החדשה? בשם הזה - 'envy_freeness_and_equitability_with_payments' ואז להחליף את השם של הפונקציה הנוכחית עם השם הזה? או להשאיר ככה והמציא שם אחר לפונקציה הראשית החדשה?

2023-01-15 20:01 UTC, erelsgl commented on fairpy/items/envy_free_approximation_division.py
> +def envy_free_approximation_division(allocation: Allocation, eps: float = 0) -> dict:
אפשר לשנות את השם של הפונקציה הנוכחית ל:
make_envy_free_and_equitable_with_payments
כי היא משנה חלוקה קיימת לחלוקה הוגנת.
והפונקציה הראשית תהיה:
find_envy_free_and_equitable_with_payments
כי היא מוצאת חלוקה חדשה.

2023-01-16 08:34 UTC, noamya-sh commented on fairpy/items/envy_free_approximation_division.py
> +def envy_free_approximation_division(allocation: Allocation, eps: float = 0) -> dict:
פיצלתי כפי שביקשת ל2 פונקציות של find_envy_free_aprximation המקבלת valuationMatrix וmake שמקבלת חלוקה, וקראתי לdivide עם find והארגומנטים הדרושים אך נזרקת שגיאה מכיוון שהאלגוריתם שלי מחזיר dict ולא Allocation

2023-01-16 10:55 UTC, eitansh28 commented on fairpy/items/envy_free_approximation_division.py
> +def envy_free_approximation_division(allocation: Allocation, eps: float = 0) -> dict:
לגבי מה שנעמיה כתב - צריך שתהיה אפשרות בפונקציה divide שהoutput יהיה מסוג dict כי במקרה שלנו אנחנו מחזירים מילון של חלוקה ותשלומים ולא אובייקט של חלוקה. בנוסף, ההמרה של הinput לAgentList קצת משבשת, אם תהיה אפשרות שהalgorithm יקבל את הinput כמו שהוא זה יהיה מצוין..

2023-01-16 13:57 UTC, erelsgl requested changes

2023-01-16 13:57 UTC, erelsgl commented on fairpy/items/envy_freeness_and_equitability_with_payments.py
> +logging.basicConfig(filename="../../my_logger_file.log", level=logging.DEBUG)
לא שמים שורות שכותבות לקובץ הלוג הראשי בקבצים פנימיים - זה שייך לתוכנית הראשית בלבד.

2023-01-16 13:57 UTC, erelsgl commented on fairpy/items/envy_freeness_and_equitability_with_payments.py
> +    logger.warning("check if %g", check_equal(allocation, evaluation, payments))
מדוע יש כאן אזהרה? האם זה מצב חריג? אם כן, צריך לפרט יותר מה הבעיה.

2023-01-16 13:57 UTC, erelsgl commented on fairpy/items/envy_free_approximation_division.py
> +def call_to_envy_free_aprximation(v: ValuationMatrix, eps: float = 0):
שם מתאים יותר, כמו בקובץ השני:
find_approximate_envy_free_with_payments

2023-01-16 13:57 UTC, erelsgl commented on fairpy/items/envy_free_approximation_division.py
> +def envy_free_approximation_division(allocation: Allocation, eps: float = 0) -> dict:
תגישו את השינוי, עם קובץ demo, ואבדוק אצלי.

2023-01-16 14:26 UTC, noamya-sh commented
תוקנו הדברים.

2023-01-20 08:03 UTC, merged