Proportional borda allocations
erelsgl/fairpy pull request #28
Opened 2023-01-13 08:38 UTC by shlomog12

added two files
1. The "Proportional Borda Allocations" algorithm for item allocation.
2. Tests file for functions of Proportional Borda Allocations

2023-01-14 22:09 UTC, erelsgl requested changes

2023-01-14 22:09 UTC, erelsgl commented on fairpy/items/proportional_borda_allocations.py
> +        return proportional_division_with_p_even(agents)
מדוע הפונקציה הראשית לא קוראת לפונקציות אחרות כגון proportional_division_with_number_of_agents_odd ?

2023-01-14 22:09 UTC, erelsgl commented on fairpy/items/proportional_borda_allocations.py
> +def proportional_division(agents: AgentList) -> Allocation:
אם זו הפונקציה הראשית, אז היא צריכה להיות בראש הקובץ.

2023-01-14 22:09 UTC, erelsgl commented on fairpy/items/test_proportional_borda_allocations.py
> +        f(agents=agents3)
בסוף הקובץ יש להוסיף תוכנית ראשית המריצה את הבדיקות בקובץ.

2023-01-16 07:15 UTC, shlomog12 commented on fairpy/items/test_proportional_borda_allocations.py
> +
בוצע

2023-01-16 07:20 UTC, shlomog12 commented on fairpy/items/proportional_borda_allocations.py
> +        return proportional_division_with_p_even(agents)
1. לאחר חשיבה מחודשת הגעתי למסקנה שהפונקציה proportional_division_with_number_of_agents_odd היא פשוט מקרה פרטי של הפונקציה הכללית ואין שום שינוי במימוש במקרה זה ולכן מחקתי אותה לגמרי.
2. הפונקציה  proportional_division_equal_number_of_items_and_players היא שונה מהפונקציה הראשית כי היא לא תמיד מחזירה חלוקה לעומת הפונקציה הראשית שתמיד תחזיר חלוקה. (אם אין פרופורציונלית הראשית תחזיר פרופורציונלית בקירוב)

2023-01-16 07:20 UTC, shlomog12 commented on fairpy/items/proportional_borda_allocations.py
> +def proportional_division(agents: AgentList) -> Allocation:
בוצע

2023-01-16 07:20 UTC, shlomog12 commented on fairpy/items/test_proportional_borda_allocations.py
> +        f(agents=agents3)
בוצע

2023-01-16 14:02 UTC, erelsgl requested changes

2023-01-16 14:02 UTC, erelsgl commented on fairpy/items/proportional_borda_allocations_demo.py
> +from fairpy.items.propm_allocation import propm_allocation
ייבוא ללא שימוש

2023-01-16 19:37 UTC, shlomog12 commented on fairpy/items/proportional_borda_allocations_demo.py
> +from fairpy.items.propm_allocation import propm_allocation
בוצע

2023-01-20 08:05 UTC, merged