Pull Request for adding bidding for envy freeness algoirthm
erelsgl/fairpy pull request #29
Opened 2023-01-13 10:44 UTC by AdiDahari

Hi Erel!

Me and Barak have cleaned-up our code to fit your repository.
2 files will be added: bidding_for_envy_freeness.py' , 'test_bidding_for_envy_freeness.py'
where the first is the implementation of the algorithm, and the second is a test file to run with testpy.

Please inform us abount any change needed.
Thanks!

2023-01-13 11:01 UTC, AdiDahari commented
minor fixes have been applied to argument types after the pull request failed. everything seems valid now

2023-01-14 22:19 UTC, erelsgl requested changes

2023-01-14 22:19 UTC, erelsgl commented on fairpy/items/test_bidding_for_envy_freeness.py
> +
בנוסף לקובץ הבדיקות, יש להוסיף קובץ עם סיומת _demo הכולל הדגמה קצרה של קריאה לאלגוריתם דרך
 fairpy.divide 
כמו שמוסבר ברידמי שלי הספריה. 
ראו דוגמה כאן:
https://github.com/erelsgl/fairpy/blob/master/fairpy/items/propm_allocation_demo.py

2023-01-14 22:19 UTC, erelsgl commented on fairpy/items/bidding_for_envy_freeness.py
> +def bidding_for_envy_freeness(bidding_matrix: ValuationMatrix) -> dict:
הפונקציה הראשית צריכה להיות הראשונה בקובץ, עם הפרדה ברורה בינה לבין הפונקציות הפנימיות.

2023-01-14 22:19 UTC, erelsgl commented on fairpy/items/test_bidding_for_envy_freeness.py
> +
יש להוסיף תוכנית ראשית המריצה את כל הבדיקות בקובץ.

2023-01-14 22:19 UTC, erelsgl commented on fairpy/items/test_bidding_for_envy_freeness.py
> +def test_full_cases():
חסרה בדיקה על בעיות גדולות אקראיות - עד כמה שזכור לי, אמרתם שבדקתם בעיות בגודל 1000 כדי לוודא שזמן הריצה סביר.
לא צריך בדיקה כזאת לכל הפונקציות - רק לפונקציה הראשית.

2023-01-15 09:31 UTC, AdiDahari commented on fairpy/items/test_bidding_for_envy_freeness.py
> +def test_full_cases():
הבעיה של בדיקה גדולה כזו שיהיה מאוד קשה לחזות ולוודא תוצאה,
מה שכן, אם זה בסדר מבחינתך, אנחנו יכולים לבצע בדיקה כזו על ערך יחיד לכל שחקן (וכל השאר אפסים), כך נוכל "לנבא" את התוצאה ולעשות בדיקה מלאה לגודל שכזה.
נכון, בדקנו על גדלים כאלה (ואף גדולים יותר) אך לא וידאנו את תוצאתם, שכן בשביל לאמת תוצאה צריך להגדיר מראש את ערכי מטריצת ההצעות.

2023-01-15 14:09 UTC, erelsgl commented on fairpy/items/test_bidding_for_envy_freeness.py
> +def test_full_cases():
בבדיקות אקראיות לא צריך לבדוק את התוצאה המדוייקת - מספיק לבדוק שהתוצאה הסופית ללא קנאה.

2023-01-15 15:15 UTC, AdiDahari commented
היי אראל,
טיפלנו בכל ההערות והתאמנו את האאוטפוט של האלגוריתם כך שיתאים לdivide.
נשמח לבדיקתך

2023-01-16 14:18 UTC, erelsgl commented
ראיתי שהוספתם בדיקות גדולות, אבל רק עם אפסים - זה אמנם בודק זמן-ריצה, אבל עובר רק בחלק קטן מהמסלולים באלגוריתם (למשל, ייתכן שבכלל לא מגיעים לתהליך של ההנחה, כי מלכתחילה אף אחד לא מקנא).

כמו שהצעתי קודם, יש להוסיף בדיקות אקראיות גדולות, ולא לבדוק את התוצאה הסופית במדוייק, אלא רק לבדוק שהתוצאה הסופית ללא קנאה.

2023-01-20 08:05 UTC, erelsgl commented
יפה מאד.

2023-01-20 08:05 UTC, merged