Fair Rent Division On a Budget algoirthm
erelsgl/fairpy pull request #30
Opened 2023-01-13 11:10 UTC by Asif-Rot

Hi Erel,

We would like to make a Pull Request and add a new folder with the name 'rent' which contains:
1. The algorithms for Fair Rent Division On a Budget.
3. The Calculation Assistance.
4. The tests.

2023-01-14 22:21 UTC, erelsgl commented
צילומי המסך לא אמורים להיות בבקשת המשיכה.

גם הקובץ 
requirements.txt
 לא צריך להיות כאן - לא שיניתם בו שום דבר חוץ מרווחים.

2023-01-14 22:23 UTC, erelsgl commented
לא צריך לשים את הקבצים בספריה, אלא יחד עם שאר הקבצים, ועם שמות קבצים בהתאם למקובל בספריה, למשל:

fair_rent_division_on_a_budget.py

fair_rent_division_on_a_budget_test.py

2023-01-14 22:25 UTC, erelsgl commented
בנוסף לקובץ הבדיקות, יש להוסיף קובץ 
fair_rent_division_on_a_budget_demo.py

הכולל הדגמה קצרה של קריאה לאלגוריתם דרך
fairpy.divide
כמו שמוסבר ברידמי של הספריה.

ראו דוגמה כאן:
https://github.com/erelsgl/fairpy/blob/master/fairpy/items/propm_allocation_demo.py

2023-01-14 22:33 UTC, erelsgl requested changes

2023-01-14 22:33 UTC, erelsgl commented on fairpy/rent/Algorithms.py
> +    "Fair Rent Division on a Budget"
הכותרת עם שמות המאמר והמחברים צריכה להיות בראש הקובץ.

2023-01-14 22:33 UTC, erelsgl commented on fairpy/rent/Algorithms.py
> +    doctest.testmod()
לשנות ל:
print(doctest.testmod())

2023-01-14 22:33 UTC, erelsgl commented on fairpy/rent/Algorithms.py
> +    agentList1 = AgentList({'Alice': {'2ndFloor': 250, 'Basement': 250, 'MasterBedroom': 500},
אפשר להעביר את הדוגמאות האלו לקובץ ה-demo.

2023-01-14 22:33 UTC, erelsgl commented on fairpy/rent/Calculation_Assistance.py
> +def build_budget_aware_graph(sigma: dict, vector_p: dict, budget: dict, agentList: AgentList) -> nx.DiGraph:
יש להוסיף דוקטסטים לכל הפונקציות.

2023-01-14 22:33 UTC, erelsgl commented on fairpy/rent/Calculation_Assistance.py
> +    doctest.testmod()
לשנות ל: print(doctest.testmod())

2023-01-17 03:55 UTC, erelsgl requested changes

2023-01-17 03:55 UTC, erelsgl commented on requirements.txt
>  more_itertools
הקובץ הזה לא אמור להיות בבקשת המשיכה. בקשת המשיכה צריכה לכלול רק את הקבצים שהוספתם.
גם התיקיה rent לא אמורה להיות כאן.

2023-01-17 03:55 UTC, erelsgl commented on fairpy/items/fair_rent_division_on_a_budget.py
> +logging.basicConfig(filename='../items/fair_rent_division_on_a_budget_logging.log', level=logging.DEBUG, format=LOG_FORMAT)
פקודות המשנות את תצורת הלוג הגלובלית לא אמורות להיות במודול - רק בתוכנית הראשית.

2023-01-19 14:50 UTC, erelsgl requested changes

2023-01-19 14:50 UTC, erelsgl commented on fairpy/items/fair_rent_division_on_a_budget.py
> +        print(f"--------THE RESULT--------")
הדפסות מתוך פונקציה נעשות רק עם logger - לא מדפיסים עם print מתוך פונקציה (כי המשתמש לא יכול לכבות את זה).

2023-01-19 18:33 UTC, Asif-Rot commented
בוצעו כל השינויים שהתבקשו. לבדיקתך.

2023-01-20 08:10 UTC, merged