Added 3 Goods & Chores Allocation Algorithms
erelsgl/fairpy pull request #31
Opened 2023-01-15 11:56 UTC by YairRaviv

2023-01-15 14:24 UTC, erelsgl requested changes

2023-01-15 14:24 UTC, erelsgl commented on fairpy/TestsGoodsChores.py
> +import unittest
הקובץ הזה לא צריך להיות בתיקייה הראשית אלא בתיקייה tests (אם אתה לא רואה אותה, אז תמשוך עדכונים מהענף הראשי).

2023-01-15 14:24 UTC, erelsgl commented on fairpy/TestsGoodsChores.py
> +    # print(allocation)
חסר דוקטסט

2023-01-15 14:24 UTC, erelsgl commented on fairpy/TestsGoodsChores.py
> +    try:
חסר דוקטסט

2023-01-15 14:24 UTC, erelsgl commented on fairpy/TestsGoodsChores.py
> +class Mytes(unittest.TestCase):
שם המחלקה צריך להתאים לתוכן שלה

2023-01-15 14:24 UTC, erelsgl commented on fairpy/TestsGoodsChores.py
> +import sys
יש לשים כותרת בראש הקובץ, הכוללת את שם המאמר, מחברי המאמר, המתכנתים והתאריך.

2023-01-15 14:24 UTC, erelsgl commented on fairpy/run.py
> +from flask_organize import app
כל האתר, כולל הספריות של פלאסק, לא אמור להיות בבקשת-המשיכה. תעבירו אותו לענף אחר או ל
-repository 
אחר.

2023-01-15 14:24 UTC, erelsgl commented on requirements.txt
> +fairpy @ git+https://github.com/erelsgl/fairpy.git
לא צריך לציין את הספריה עצמה בקובץ הדרישות של עצמה.

2023-01-15 14:24 UTC, erelsgl commented on requirements.txt
> +flask
הספריה לא אמורה להיות תלויה בפלאסק.
לכן קובץ ה-requirements
לא אמור להשתנות, ולא אמור להופיע בבקשת המשיכה.

2023-01-15 14:24 UTC, erelsgl commented on fairpy/goods_chores.py
> +    "Fair allocation of indivisible goods and chores" by  Ioannis Caragiannis ,
הכותרת עם שם המאמר והמתכנתים צריכה להיות בראש הקובץ.

2023-01-15 14:24 UTC, erelsgl commented on fairpy/TestsGoodsChores.py
> +import unittest
בנוסף לקובץ הבדיקות, יש להוסיף קובץ עם סיומת _demo הכולל הדגמה קצרה של קריאה לאלגוריתם דרך
fairpy.divide
כמו שמוסבר ברידמי של הספריה.
ראו דוגמה כאן:
https://github.com/erelsgl/fairpy/blob/master/fairpy/items/propm_allocation_demo.py

2023-01-15 14:24 UTC, erelsgl commented on fairpy/goods_chores.py
> +    raise exception("the algorithem sould alwayse return an allocation")
יש לתקן 3 שגיאות באנגלית

2023-01-16 19:31 UTC, chkp-yairra commented
Done.

2023-01-17 04:13 UTC, erelsgl requested changes

2023-01-17 04:13 UTC, erelsgl commented on tests/TestsGoodsChores.py
> +    def test1(self):
צריך לתת לבדיקות שמות משמעותיים - לא מספרים.

2023-01-17 04:13 UTC, erelsgl commented on tests/TestsGoodsChores.py
> +def is_PO(agents: AgentList, result: dict):
לא הצלחתי להבין מה בדיוק הפונקציה הזו עושה, ומה האלגוריתם שלה?

2023-01-17 04:13 UTC, erelsgl commented on fairpy/templates/algorithm1.html
> +
כל התיקיה templates לא אמורה להיות בבקשת המשיכה. היא שייכת לאתר. צריך להעביר אותה לענף נפרד או לרפוסיטורי נפרד.

2023-01-17 04:13 UTC, erelsgl commented on fairpy/items/goods_chores.py
> +"""
הכותרת צריכה להיות ממש בתחילת הקובץ.

2023-01-17 04:13 UTC, erelsgl commented on fairpy/items/goods_chores.py
> +logger.basicConfig(format='[%(levelname)s - %(asctime)s] - %(message)s', level=logging.INFO)
פקודות שמשנות את תצורת הלוג הכללית לא אמורות להיות בתוך מודול, אלא רק בתוכנית הראשית

2023-01-17 04:13 UTC, erelsgl commented on fairpy/items/goods_chores_demo.py
> +print(Double_RoundRobin_Algorithm(DoubleRoundRobinInput))
בקובץ זה יש להשתמש בפונקציה fairpy.divide כמו כאן:

https://github.com/erelsgl/fairpy/blob/master/fairpy/items/propm_allocation_demo.py

2023-01-17 04:13 UTC, erelsgl commented on fairpy/items/goods_chores.py
> +
חסרה פקודה return

2023-01-17 04:13 UTC, erelsgl commented on fairpy/items/goods_chores.py
> +
וחסרה החריגה שהיתה כאן קודם

2023-01-17 04:13 UTC, erelsgl commented on fairpy/items/goods_chores.py
> +
חסר דוקטסט

2023-01-17 06:05 UTC, chkp-yairra commented on tests/TestsGoodsChores.py
> +def is_PO(agents: AgentList, result: dict):
הפונקציה הזו בודקת האם חלוקה מסויימת ל2 סוכנים היא יעילה פארטו או לא.
האלגוריתם שלה הוא מעבר על כל החלוקות האפשריות , אם עבור אחת מהחלוקות האפשריות מתקבל מצב שבו אחד מהסוכנים מרוויח יותר והסוכן השני לא מפסיד נחזיר False מכיוון שחלוקה שכזו יעילה יותר מהחלוקה הנוכחית.

2023-01-17 06:29 UTC, chkp-yairra commented on fairpy/items/goods_chores_demo.py
> +print(Double_RoundRobin_Algorithm(DoubleRoundRobinInput))
השימוש בפונקציה divide דורש ממני להחזיר ב3 האלגוריתמים List כי היא הפוכת את הoutput להיות מסוג Allocation , 
והאלגוריתמים כרגע מחזירים dict, זה דורש ממני refactor משמעותי מאוד לכל האלגוריתמים וגם לכל היוניטסטים והדוקטסטים בהתאמה , זה משהו שהוא קריטי מבחינת הדמו ? כי בכל זאת אני מדגים שם בדיוק איך אני קורא לאלגוריתמים (הוספתי את שמות הארגומנטים שיהיה ברור יותר)

2023-01-17 07:10 UTC, chkp-yairra commented
תיקנתי את ההערות.

2023-01-18 15:11 UTC, erelsgl requested changes

2023-01-18 15:11 UTC, erelsgl commented on requirements.txt
> +scs
הקובץ הזה לא צריך להיות בכלל בבקשת המשיכה. הוא לא אמור להשתנות. לא ברור לי למה הוא כאן.

2023-01-18 15:11 UTC, erelsgl commented on tests/TestsGoodsChores.py
> +def is_PO(agents: AgentList, result: dict):
יפה מאד. עכשיו אני מבין. תוסיף את ההסבר הזה בתיעוד של הפונקציה.

2023-01-18 15:11 UTC, erelsgl commented on tests/TestsGoodsChores.py
> +    def test2(self):
צריך לתת לבדיקות שמות משמעותיים - לא מספרים.

2023-01-18 15:11 UTC, erelsgl commented on tests/TestsGoodsChores.py
> +    "Fair allocation of indivisible goods and chores" by  Ioannis Caragiannis ,
שם הקובץ צריך להיות test_goods_chores.py.
זה חשוב כי אחרת pytest לא מריץ את הבדיקות.

תריצו את הקובץ הזה על המחשב שלכם ותראו שחלק מהבדיקות לא עוברות.

2023-01-18 15:57 UTC, chkp-yairra commented
Done

2023-01-19 15:05 UTC, erelsgl commented on tests/test_goods_chores.py
> +class Goods_Chores_Tests(unittest.TestCase):
המחלקה הזאת מופיעה פעמיים - מה הגירסה הנכונה שלה?

2023-01-19 15:22 UTC, YairRaviv commented on tests/test_goods_chores.py
> +class Goods_Chores_Tests(unittest.TestCase):
מחקתי את הכפילות ודחפתי

2023-01-20 08:06 UTC, erelsgl commented
יפה מאד.

2023-01-20 08:06 UTC, merged