Fair Course Allocation
erelsgl/fairpy pull request #33
Opened 2023-01-17 08:45 UTC by TahelZecharia

2023-01-17 11:13 UTC, TahelZecharia commented
Fair Couse Allocation

2023-01-18 16:12 UTC, erelsgl requested changes

2023-01-18 16:12 UTC, erelsgl commented on fairpy/items/fair_course_allocation_implementation_test.py
> +            [1.9, 0.40999999999999986, 1.6, 1.2, 0.8],
ערכים צפויים לא צריכים להיות ברמת דיוק גבוהה כמו 0.40999999999999986, כי זה עלול להיכשל במחשב עם רמת דיוק אחרת. עדיף לעגל את התוצאות כך שיהיו עקביות.
אותו הדבר חוזר במקומות נוספים בקובץ.

2023-01-18 16:12 UTC, erelsgl commented on fairpy/items/fair_course_allocation_implementation_test.py
> +    assert score(placements, capacity) == 7.874007874011811
כשיש בדיקה עם תוצאה כל כך מדוייקת, צריך להסביר מדוע - למה דווקא זה הערך הנכון?

2023-01-20 07:07 UTC, erelsgl requested changes

2023-01-20 07:07 UTC, erelsgl commented on fairpy/items/fair_course_allocation_demo.py
> +allocation = general_course_allocation(utilities, capacity, num_of_courses)
יש לקרוא לפונקציה דרך fairpy.divide. זאת, כדי לוודא שפורמט הקלט והפלט מתאימים למקובל בספריה.

2023-01-20 07:07 UTC, erelsgl commented on fairpy/items/fair_course_allocation_implementation.py
> +Article Name:
ההערה הזאת צריכה להיות ממש בראש הקובץ.

2023-01-20 07:07 UTC, erelsgl commented on fairpy/items/fair_course_allocation_implementation.py
> +
אפשר להשתמש ב ellipsis של דוקטסט כדי לבדוק שיש פלט בפורמט כלשהו, אבל להתעלם מהפרטים שלו. יש הסבר כאן: https://pymotw.com/3/doctest/

2023-01-23 18:28 UTC, merged