Course allocation by proxy auction
erelsgl/fairpy pull request #34
Opened 2023-01-17 16:26 UTC by AvihuuGoren

Created a pull request please merge or comment.

2023-01-19 16:02 UTC, erelsgl requested changes

2023-01-19 16:02 UTC, erelsgl commented on fairpy/items/test_course_allocation.py
> +@pytest.mark.xfail()
לא כך בודקים שהפקודה זורקת חריגה. הסברתי בשיעור איך עושים את זה.

2023-01-19 16:02 UTC, erelsgl commented on fairpy/items/test_course_allocation.py
> +        course_allocation(agents,250,["c1","c2","c3","c4"],1)
יפה, אבל צריך גם לבדוק כאן שהתוצאות הגיוניות (למשל שכל שחקן מקבל חבילה הוגנת של קורסים).

2023-01-23 11:53 UTC, erelsgl commented on fairpy/items/test_course_allocation.py
> +
יש להשתמש ב fairpy.divide כמו בקישור למעלה. זאת, כדי לוודא שפורמט הקלט והפלט של הפונקציה שלך מתאים למקובל בספריה.

2023-01-23 11:54 UTC, erelsgl commented on fairpy/items/test_course_allocation.py
> +
התוכנית הראשית עם המסלול שכתבת לא עובדת בכל המחשבים. תוכנית ראשית כללית יותר היא:
    pytest.main(["-v",__file__])
(הפרמטר __file__ הוא המסלול המלא של הקובץ הנוכחי).

2023-01-23 11:55 UTC, erelsgl commented
יפה. כתבתי לך למעלה כמה הערות קטנות.

2023-01-23 12:28 UTC, AvihuuGoren commented on fairpy/items/test_course_allocation.py
> +
המסלול המלא כמו שכתבתי? כי התיקייה tests  היא חלק מהפרויקט

2023-01-23 14:39 UTC, erelsgl commented on fairpy/items/test_course_allocation.py
> +
לא, אתה פשוט כותב __file__ (עם שני קוים תחתיים לפני ואחרי). זה "משתנה קסם" שערכו תמיד שווה למסלול של הקובץ הנוכחי.

2023-01-23 15:05 UTC, AvihuuGoren commented on fairpy/items/test_course_allocation.py
> +
תודה תיקנתי

2023-01-23 15:10 UTC, AvihuuGoren commented
> יפה. כתבתי לך למעלה כמה הערות קטנות.

הכל תוקן

2023-01-23 15:13 UTC, merged