Adding new fair division algorithms
erelsgl/fairpy pull request #35
Opened 2023-01-17 21:15 UTC by ItayHasidi

Sequential, Restricted simple, Singles Doubles, Iterated singles doubles, S1, L1, Top down, Top down alternating, Bottom up, Bottom up alternating, Trump

2023-01-17 21:16 UTC, ItayHasidi commented
Adding new fair division algorithms

2023-01-18 16:15 UTC, erelsgl commented
חסר קובץ בדיקות יחידה (בתיקיה tests, מתחיל ב test_)
וכן קובץ הדגמה המפעיל את האלגוריתמים דרך fairpy.divide, כמו כאן:

https://github.com/erelsgl/fairpy/blob/master/fairpy/items/propm_allocation_demo.py

2023-01-18 22:53 UTC, ItayHasidi commented
הוספת קובץ demo וקובץ test

2023-01-19 15:41 UTC, erelsgl requested changes

2023-01-19 15:41 UTC, erelsgl commented on fairpy/items/two_players_fair_division_utils.py
> +    return sorted_lst
תוסיפו תוכנית ראשית שמריצה את הבדיקות, כמו בקובץ הראשי

2023-01-19 15:41 UTC, erelsgl commented on tests/test_two_players_fair_division.py
> +
צריך להוסיף בדיקות על קלטים אקראיים גדולים.

2023-01-19 15:41 UTC, erelsgl commented on tests/test_two_players_fair_division.py
> +
תוסיפו כאן תוכנית ראשית שמריצה את כל הבדיקות.

2023-01-19 15:41 UTC, erelsgl commented on tests/test_two_players_fair_division.py
> +from fairpy import fairpy
תוסיפו בראש הקובץ כותרת עם שמות המאמר, המחברים והמתכנתים (אתם), כמו בקובץ הראשי

2023-01-19 15:41 UTC, erelsgl commented on fairpy/items/two_players_fair_division_demo.py
> +print("sequential:\n", sequential(agents=[Alice, George], items=items))
כאן יש להשתמש ב fairpy.divide. זאת כדי לוודא שפורמט הקלט והפלט מתאים למקובל בספריה.

2023-01-21 13:21 UTC, ItayHasidi commented
תיקנו את הדגשים

2023-01-21 17:14 UTC, merged